### ISSUE TITLE
`prepareGraphQLPost` fails on empty message body

### ISSUE THREAD

**Issue by performantdata** [sangria-graphql/sangria-akka-http#13]
Running the [`sangria-akka-http-example`](https://github.com/sangria-graphql/sangria-akka-http-example), I see the following output:
```shell
$ curl -X POST 'http://localhost:8080/graphql?query=%7Bhero+%7Bname,+friends+%7Bname%7D%7D%7D' -H "Content-Type:application/json" -d ''
{"errors":[{"message":"Could not extract `query` from request.\nPlease confirm you have included a valid GraphQL query either as a QueryString parameter, or in the body of your request.","locations":null}]}%
$ curl -X POST 'http://localhost:8080/graphql?query=%7Bhero+%7Bname,+friends+%7Bname%7D%7D%7D' -H "Content-Type:application/json" -d '{}'
{"data":{"hero":{"name":"R2-D2","friends":[{"name":"Luke Skywalker"},{"name":"Han Solo"},{"name":"Leia Organa"}]}}}%
```
I'm passing the query as a query parameter as allowed by [the GraphQL POST recommendations](https://graphql.org/learn/serving-over-http/#post-request). Notice that the only difference between the two `curl` commands is that I'm passing an empty body in the case that fails.

I came across this oversight while reviewing the `prepareGraphQLPost` code.

**Comment by performantdata** [comment]
@nickhudkins, [sounds like you wrote this](https://gitter.im/sangria-graphql/sangria?at=612a3e0499b7d97528dc5069), so what's your take?

**Comment by performantdata** [comment]
I also think that the logic is flawed in that it tries to parse the HTTP message body first as JSON, then as a GraphQL query, without ever checking the `Content-Type`. It should only try to parse as those if the respective `Content-Type` is declared:
> A standard GraphQL POST request should use the `application/json` content type, and include a JSON-encoded body

> If the "application/graphql" Content-Type header is present, treat the HTTP POST body contents as the GraphQL query string.

**Comment by performantdata** [comment]
I also noticed that you're not following [the spec](https://spec.graphql.org/June2018/#sec-Response-Format) by returning a `null` `data` field in the error response when execution has already begun at the time of the error.
> If the operation included execution, the response map must contain an entry with key `data`.

> If an error was encountered during the execution that prevented a valid response, the `data` entry in the response should be `null`.

**Comment by nickhudkins** [comment]
An empty body feels a bit odd, but I suppose if `operationName` and `variables` are optional, there is nothing to say that the POST with `application/json` couldn't have the query in the Query String. Seems like an oversight to not check Content-Type as well. Thanks!
